"""Safe, network-free integration contracts for Relay."""

from .agent import (
    AgentBudget,
    AgentCapability,
    AgentResultEnvelope,
    AgentTaskEnvelope,
    AgentTaskKind,
    ClassificationResult,
    DeterministicMockAgentAdapter,
    EvidencePacketResult,
    ReproductionResult,
    ResultAcceptance,
    ScopedFixResult,
    validate_agent_task,
    validate_result,
)
from .errors import ContractValidationError, ValidationCode
from .github import (
    AddLabels,
    CreateBranch,
    CreateDraftPullRequest,
    DeliveryIdentity,
    FakeGitHubAdapter,
    GitHubCapability,
    GitHubWebhookEnvelope,
    InMemoryDeliveryDeduplicator,
    PostIssueComment,
    RepositoryAllowlist,
    RepositoryIdentity,
    verify_sha256_signature,
)

__all__ = [
    "AddLabels",
    "AgentBudget",
    "AgentCapability",
    "AgentResultEnvelope",
    "AgentTaskEnvelope",
    "AgentTaskKind",
    "ClassificationResult",
    "ContractValidationError",
    "CreateBranch",
    "CreateDraftPullRequest",
    "DeliveryIdentity",
    "DeterministicMockAgentAdapter",
    "EvidencePacketResult",
    "FakeGitHubAdapter",
    "GitHubCapability",
    "GitHubWebhookEnvelope",
    "InMemoryDeliveryDeduplicator",
    "PostIssueComment",
    "RepositoryAllowlist",
    "RepositoryIdentity",
    "ReproductionResult",
    "ResultAcceptance",
    "ScopedFixResult",
    "ValidationCode",
    "validate_agent_task",
    "validate_result",
    "verify_sha256_signature",
]
