"""initial lifecycle schema

Revision ID: 0001
Revises:
Create Date: 2026-09-06 00:59:38.594564

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issue_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("workspace_released", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_sessions_issue_id"), ["issue_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_sessions_state"), ["state"], unique=False)

    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issue_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artifacts_issue_id"), ["issue_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifacts_session_id"), ["session_id"], unique=False)

    op.create_table(
        "audit_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("correlation_id", sa.String(length=60), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_entries_correlation_id"), ["correlation_id"], unique=False
        )

    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_messages_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issue_id", sa.String(length=36), nullable=True),
        sa.Column("source", sa.String(length=60), nullable=False),
        sa.Column("delivery_id", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "delivery_id", name="uq_event_delivery"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_issue_id"), ["issue_id"], unique=False)

    op.create_table(
        "human_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issue_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("human_decisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_human_decisions_issue_id"), ["issue_id"], unique=False)

    op.create_table(
        "information_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issue_id", sa.String(length=36), nullable=False),
        sa.Column("issue_revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("information_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_information_requests_issue_id"), ["issue_id"], unique=False
        )

    op.create_table(
        "issue_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issue_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issue_id", "revision", name="uq_issue_revision"),
    )
    with op.batch_alter_table("issue_revisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_issue_revisions_issue_id"), ["issue_id"], unique=False)

    op.create_table(
        "issues",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("repository_id", sa.String(length=36), nullable=False),
        sa.Column("external_number", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("owner_team", sa.String(length=120), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "external_number", name="uq_issue_repo_number"),
    )
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_issues_owner_team"), ["owner_team"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_issues_repository_id"), ["repository_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_issues_state"), ["state"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issue_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("idempotency_key", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("run_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_issue_id"), ["issue_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)

    op.create_table(
        "pull_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issue_id", sa.String(length=36), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pull_requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pull_requests_issue_id"), ["issue_id"], unique=False)

    op.create_table(
        "repositories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("full_name"),
    )
    op.create_table(
        "session_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("session_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_session_events_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "session_outputs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("session_outputs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_session_outputs_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "transition_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issue_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    with op.batch_alter_table("transition_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transition_attempts_issue_id"), ["issue_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transition_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transition_attempts_issue_id"))

    op.drop_table("transition_attempts")
    with op.batch_alter_table("session_outputs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_outputs_session_id"))

    op.drop_table("session_outputs")
    with op.batch_alter_table("session_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_events_session_id"))

    op.drop_table("session_events")
    op.drop_table("repositories")
    with op.batch_alter_table("pull_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pull_requests_issue_id"))

    op.drop_table("pull_requests")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_issue_id"))

    op.drop_table("jobs")
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issues_state"))
        batch_op.drop_index(batch_op.f("ix_issues_repository_id"))
        batch_op.drop_index(batch_op.f("ix_issues_owner_team"))

    op.drop_table("issues")
    with op.batch_alter_table("issue_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issue_revisions_issue_id"))

    op.drop_table("issue_revisions")
    with op.batch_alter_table("information_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_information_requests_issue_id"))

    op.drop_table("information_requests")
    with op.batch_alter_table("human_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_human_decisions_issue_id"))

    op.drop_table("human_decisions")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_issue_id"))

    op.drop_table("events")
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_messages_session_id"))

    op.drop_table("conversation_messages")
    with op.batch_alter_table("audit_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_entries_correlation_id"))

    op.drop_table("audit_entries")
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifacts_session_id"))
        batch_op.drop_index(batch_op.f("ix_artifacts_issue_id"))

    op.drop_table("artifacts")
    with op.batch_alter_table("agent_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_sessions_state"))
        batch_op.drop_index(batch_op.f("ix_agent_sessions_issue_id"))

    op.drop_table("agent_sessions")
    # ### end Alembic commands ###
