"""Persistence ports consumed by the domain. Implemented under app.persistence."""

from __future__ import annotations

import uuid
from collections.abc import Sequence
from datetime import datetime
from typing import Protocol

from app.domain.models import (
    AgentSession,
    AuditEntry,
    ConversationMessage,
    Event,
    Evidence,
    HumanDecision,
    InformationRequest,
    Issue,
    IssueRevision,
    Job,
    PullRequestState,
    Repository,
    ReviewerRouting,
    SessionEvent,
    SessionOutput,
    TransitionAttempt,
)
from app.domain.states import IssueState, SessionState


class Clock(Protocol):
    def now(self) -> datetime: ...


class UnitOfWork(Protocol):
    """One transaction. `lock_issue` provides per-issue serialization."""

    def __enter__(self) -> UnitOfWork: ...

    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...

    def lock_issue(self, issue_id: uuid.UUID) -> None: ...

    # repositories
    def get_repository(self) -> Repository | None: ...

    def add_repository(self, repository: Repository) -> None: ...

    # issues
    def add_issue(self, issue: Issue) -> None: ...

    def save_issue(self, issue: Issue) -> None: ...

    def get_issue(self, issue_id: uuid.UUID) -> Issue | None: ...

    def get_issue_by_number(self, repository_id: uuid.UUID, number: int) -> Issue | None: ...

    def list_issues(
        self, *, state: IssueState | None = None, owner_team: str | None = None
    ) -> Sequence[Issue]: ...

    def add_revision(self, revision: IssueRevision) -> None: ...

    def list_revisions(self, issue_id: uuid.UUID) -> Sequence[IssueRevision]: ...

    # events
    def add_event(self, event: Event) -> None: ...

    def get_event_by_delivery(self, source: str, delivery_id: str) -> Event | None: ...

    def list_events(self, issue_id: uuid.UUID) -> Sequence[Event]: ...

    def count_events(self) -> int: ...

    # transition attempts
    def add_attempt(self, attempt: TransitionAttempt) -> None: ...

    def list_attempts(self, issue_id: uuid.UUID) -> Sequence[TransitionAttempt]: ...

    def get_attempt_for_event(self, event_id: uuid.UUID) -> TransitionAttempt | None: ...

    def list_all_attempts(self) -> Sequence[TransitionAttempt]: ...

    # questions
    def add_question(self, question: InformationRequest) -> None: ...

    def save_question(self, question: InformationRequest) -> None: ...

    def get_question(self, question_id: uuid.UUID) -> InformationRequest | None: ...

    def list_questions(
        self, issue_id: uuid.UUID, revision: int | None = None
    ) -> Sequence[InformationRequest]: ...

    # evidence
    def add_evidence(self, evidence: Evidence) -> None: ...

    def list_evidence(self, issue_id: uuid.UUID) -> Sequence[Evidence]: ...

    # decisions
    def add_decision(self, decision: HumanDecision) -> None: ...

    def list_decisions(self, issue_id: uuid.UUID) -> Sequence[HumanDecision]: ...

    # jobs
    def add_job(self, job: Job) -> None: ...

    def save_job(self, job: Job) -> None: ...

    def get_job(self, job_id: uuid.UUID) -> Job | None: ...

    def get_job_by_key(self, idempotency_key: str) -> Job | None: ...

    def list_jobs(self, issue_id: uuid.UUID | None = None) -> Sequence[Job]: ...

    # sessions
    def add_session(self, session: AgentSession) -> None: ...

    def save_session(self, session: AgentSession) -> None: ...

    def get_session(self, session_id: uuid.UUID) -> AgentSession | None: ...

    def list_sessions(
        self, *, issue_id: uuid.UUID | None = None, state: SessionState | None = None
    ) -> Sequence[AgentSession]: ...

    def add_session_event(self, event: SessionEvent) -> None: ...

    def list_session_events(self, session_id: uuid.UUID) -> Sequence[SessionEvent]: ...

    def add_message(self, message: ConversationMessage) -> None: ...

    def list_messages(self, session_id: uuid.UUID) -> Sequence[ConversationMessage]: ...

    def add_output(self, output: SessionOutput) -> None: ...

    def list_outputs(self, session_id: uuid.UUID) -> Sequence[SessionOutput]: ...

    # pull requests
    def add_pull_request(self, pr: PullRequestState) -> None: ...

    def save_pull_request(self, pr: PullRequestState) -> None: ...

    def list_pull_requests(self, issue_id: uuid.UUID) -> Sequence[PullRequestState]: ...

    # reviewer routing (trusted CODEOWNERS adapter outcomes)
    def add_reviewer_routing(self, routing: ReviewerRouting) -> None: ...

    def list_reviewer_routings(self, issue_id: uuid.UUID) -> Sequence[ReviewerRouting]: ...

    # audit
    def add_audit(self, entry: AuditEntry) -> None: ...

    def list_audit(self, correlation_id: str) -> Sequence[AuditEntry]: ...


class UnitOfWorkFactory(Protocol):
    def __call__(self) -> UnitOfWork: ...
